### ISSUE TITLE
Invalid key error

### ISSUE THREAD

**Issue by izayoi256** [polyswarm/ppdns-chrome-extension#47]
I just noticed that the rewards from PPDNS have been stopped since 11th August.

I tried re-installing the extension manually and via Chrome Web Store, and I also regenerated the API keys, but none of them worked.

How can I fix this? 

OS: Linux Mint
Browser: Google Chrome 129.0.6668.70（Official Build） （64 ビット）

**Comment by alanjds** [comment]
Thanks for reporting the issue @izayoi256. The extension shows a message every time it cannot talk to our services, but does not show a message when it finally is able to do it. We are considering to change that behavior.

As you said to had already regenerated your API Key, your data is probably being ingested correctly.

About the distribution, we are already investigating the cause. The distributions will occur retroactively.

Best regards, Alan (a PolySwarm Dev).

**Comment by LuckRen** [comment]
![Uploading PixPin_2024-09-29_10-26-04.png…]()

**Comment by LuckRen** [comment]
![PixPin_2024-09-29_10-26-04](https://github.com/user-attachments/assets/6b5e90e8-3084-441d-822a-b6462b2fb97a)

**Comment by izayoi256** [comment]
@alanjds 

The problem is that the new API key won't even be accepted by the app like the image below.
![Peek 2024-10-07 12-11](https://github.com/user-attachments/assets/db7c56ae-d6d0-44d9-b99b-9db3883aede3)

**Comment by alanjds** [comment]
> The problem is that the new API key won't even be accepted by the app like the image below.

I see. I found this issue during the changes being done this week. Looks like the API Key is not being recognized anymore, as some other service changed behind my back :) .

I expect a new version to be released this week, fixing this and providing better error messages.

**Comment by alanjds** [comment]
@izayoi256 I see that you closed the issue as "completed". As a new version got released to handle the issue, I will assume this as a confirmation that it is fixed.

Please reopen this issue if still broken. And thanks again for reporting 👍.

Best regards.

**Comment by izayoi256** [comment]
@alanjds 
Oh, sorry for closing the issue without any responses. Yes, the problem itself was fixed now for me.
Thanks for your quick responses and fix.
